#!/usr/bin/env ruby

require './hash_checker'

puts 'Use Ctrl+C to exit program.'
hash = HashChecker.new

loop do
  print('Enter your Hash: ')
  trap('SIGINT') do
    puts("\n")
    exit
  end
  out = hash.check(gets.chomp)
  out.empty? ? puts("\e[31m#{'No hash matches found!'}\e[0m") : puts("\e[32m#{out}\e[0m")
  puts
end
